// 配方页共用的物品外观；数量、标签和条件由每个示例按需补充。
export const recipeItems = {
  palmPlanks: {icon: 'palm_planks', name: '棕榈木板', id: 'default:palm_planks'},
  oakPlanks: {icon: 'oak_planks', name: '橡木木板', id: 'minecraft:oak_planks'},
  palmLog: {icon: 'palm_log', name: '棕榈原木', id: 'default:palm_log'},
  strippedPalmLog: {icon: 'stripped_palm_log', name: '去皮棕榈原木', id: 'default:stripped_palm_log'},
  stick: {icon: 'stick', name: '木棒', id: 'minecraft:stick'},
  chest: {icon: 'chest', name: '箱子', id: 'minecraft:chest'},
  woodenPickaxe: {icon: 'wooden_pickaxe', name: '木镐', id: 'minecraft:wooden_pickaxe'},
  diamondSword: {icon: 'diamond_sword', name: '钻石剑', id: 'minecraft:diamond_sword'},
  paper: {icon: 'paper', name: '纸', id: 'minecraft:paper'},
  topaz: {icon: 'topaz', name: '黄玉', nameColor: '#ffaa00', id: 'default:topaz'},
  topazSword: {icon: 'topaz_sword', name: '黄玉剑', nameColor: '#ffaa00', id: 'default:topaz_sword'},
  topazShovel: {icon: 'topaz_shovel', name: '黄玉锹', nameColor: '#ffaa00', id: 'default:topaz_shovel'},
  topazCrossbow: {icon: 'topaz_crossbow', name: '黄玉弩', nameColor: '#ffaa00', id: 'default:topaz_crossbow'},
  topazBow: {icon: 'topaz_bow', name: '黄玉弓', nameColor: '#ffaa00', id: 'default:topaz_bow'},
  topazPickaxe: {icon: 'topaz_pickaxe', name: '黄玉镐', nameColor: '#ffaa00', id: 'default:topaz_pickaxe'},
  topazOre: {icon: 'topaz_ore', name: '黄玉矿石', id: 'default:topaz_ore'},
  deepslateTopazOre: {icon: 'deepslate_topaz_ore', name: '深层黄玉矿石', id: 'default:deepslate_topaz_ore'},
  chineseLantern: {icon: 'chinese_lantern', name: '中式灯笼', id: 'default:chinese_lantern'},
  torch: {icon: 'torch', name: '火把', id: 'minecraft:torch'},
  cobblestone: {icon: 'cobblestone', name: '圆石', id: 'minecraft:cobblestone'},
  enchantedCobblestone: {icon: 'enchanted_cobblestone', name: '附魔圆石', nameColor: '#ff55ff', id: 'default:enchanted_cobblestone'},
  crossbow: {icon: 'crossbow_standby', name: '弩', id: 'minecraft:crossbow'},
  bow: {icon: 'bow', name: '弓', id: 'minecraft:bow'},
  blazeRod: {icon: 'blaze_rod', name: '烈焰棒', id: 'minecraft:blaze_rod'},
  stone: {icon: 'stone', name: '石头', id: 'minecraft:stone'},
  boltTemplate: {icon: 'bolt_armor_trim_smithing_template', name: '锻造模板', id: 'minecraft:bolt_armor_trim_smithing_template', lore: [{text: '镶铆盔甲纹饰', color: '#ffaa00'}]},
  goldIngot: {icon: 'gold_ingot', name: '金锭', id: 'minecraft:gold_ingot'},
};

export const recipeBookRecipes = [
  {
    id: 'default:palm_planks', category: 'building', group: 'planks', shapeless: true,
    pattern: ['   ', ' L ', '   '],
    ingredients: {L: recipeItems.palmLog},
    result: {...recipeItems.palmPlanks, count: 4},
  },
  {
    id: 'minecraft:oak_planks', category: 'building', group: 'planks', shapeless: true,
    pattern: ['   ', ' L ', '   '],
    ingredients: {L: {icon: 'oak_log', name: '橡木原木', id: 'minecraft:oak_log'}},
    result: {...recipeItems.oakPlanks, count: 4},
  },
  {
    id: 'minecraft:chest', category: 'misc',
    pattern: ['PPP', 'P P', 'PPP'],
    ingredients: {P: {...recipeItems.oakPlanks, tags: ['minecraft:planks']}},
    result: recipeItems.chest,
  },
  {
    id: 'minecraft:wooden_pickaxe', category: 'equipment',
    pattern: ['PPP', ' S ', ' S '],
    ingredients: {P: {...recipeItems.oakPlanks, tags: ['minecraft:wooden_tool_materials']}, S: recipeItems.stick},
    result: recipeItems.woodenPickaxe,
  },
  {
    id: 'minecraft:bread', category: 'misc',
    pattern: ['   ', 'WWW', '   '],
    ingredients: {W: {icon: 'wheat', name: '小麦', id: 'minecraft:wheat'}},
    result: {icon: 'bread', name: '面包', id: 'minecraft:bread'},
  },
  {
    id: 'minecraft:redstone_torch', category: 'redstone',
    pattern: ['   ', ' R ', ' S '],
    ingredients: {R: {icon: 'redstone', name: '红石粉', id: 'minecraft:redstone'}, S: recipeItems.stick},
    result: {icon: 'redstone_torch', name: '红石火把', id: 'minecraft:redstone_torch'},
  },
];
